export const PURCHASE_COURSE_START = 'PURCHASE_COURSE_START';
export const PURCHASE_COURSE_SUCCESS = 'PURCHASE_COURSE_SUCCESS';
export const PURCHASE_COURSE_FAIL = 'PURCHASE_COURSE_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';


export const FETCH_COURSE_START = 'FETCH_COURSE_START';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSE_FAIL = 'FETCH_COURSE_FAIL';





export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';