export const ADD_COURSE_START = 'ADD_COURSE_START';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';
export const ADD_COURSE_INIT = 'ADD_INIT';

export const FETCH_COURSES_START = 'FETCH_COURSE_START';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSES_FAIL = 'FETCH_COURSE_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';